import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Easy Commerce',
  description: 'Generated by Next.js',
}
import NavigationListener from '@/components/n8n/NavigationListener';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import TopLoader from '@/components/TopLoader';
import RouteProgress from '@/components/RouteProgress';

import { AuthProvider } from '@/contexts/AuthContext';
import { CartProvider } from '@/contexts/CartContext';
import { ToastProvider } from '@/contexts/ToastContext';
import { ToastContainer } from '@/components/Toast';
import Script from 'next/script';
import ChatBot from '@/components/ChatBot';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
     
      </head>
      <body>
        <Script src="https://cdn.botpress.cloud/webchat/v3.3/inject.js" strategy="afterInteractive" />
        <Script src="https://files.bpcontent.cloud/2025/08/28/15/20250828154347-8WOMCN1E.js" strategy="afterInteractive" />
        <AuthProvider>
          <ToastProvider>
            <CartProvider>
              {/* Keep existing NextTopLoader for router-driven transitions if desired */}
              {/* <TopLoader /> */}
              <RouteProgress />
              <NavigationListener />
              <Navbar />
              <main className="pt-0 lg:pt-0 "> 
                {children}
              </main>
              <Footer />

              <ToastContainer />
              <ChatBot />
            </CartProvider>
          </ToastProvider>
        </AuthProvider>
        
       
      
      </body>
    </html>
  )
}